"""Fallback chain manager for LLM providers."""

import logging
import time
from dataclasses import dataclass, field
from typing import Dict, List

from zlsde.providers.base import LLMProvider
from zlsde.providers.exceptions import AllProvidersFailedError, ProviderError

logger = logging.getLogger(__name__)


@dataclass
class ProviderStats:
    """Statistics for a single provider.
    
    Tracks usage metrics including success/failure counts, response times,
    and token usage for monitoring and optimization.
    """
    provider_name: str
    successful_calls: int = 0
    failed_calls: int = 0
    total_response_time_ms: float = 0.0
    total_tokens: int = 0


class FallbackChainManager:
    """Manages fallback chain of LLM providers.
    
    This class orchestrates multiple LLM providers in a fallback chain,
    automatically trying the next provider when one fails. It also tracks
    usage statistics for monitoring and optimization.
    """
    
    def __init__(self, providers: List[LLMProvider]):
        """Initialize with ordered list of providers.
        
        Args:
            providers: List of LLM providers in fallback order.
                      Only available providers will be used.
        
        Raises:
            ValueError: If no providers are available
        """
        # Filter to only available providers
        self.providers = [p for p in providers if p.is_available()]
        
        if not self.providers:
            raise ValueError("No providers available")
        
        # Initialize statistics for each provider
        self.stats: Dict[str, ProviderStats] = {
            p.get_provider_name(): ProviderStats(p.get_provider_name())
            for p in self.providers
        }
        
        logger.info(f"Initialized fallback chain with {len(self.providers)} providers: "
                   f"{[p.get_provider_name() for p in self.providers]}")
    
    def generate_label(self, prompt: str, max_tokens: int = 20) -> str:
        """Generate label with automatic fallback.
        
        Tries each provider in order until one succeeds. Tracks statistics
        for each attempt including response time and success/failure counts.
        
        Args:
            prompt: Input prompt for label generation
            max_tokens: Maximum tokens in response
            
        Returns:
            Generated label text from the first successful provider
            
        Raises:
            AllProvidersFailedError: If all providers fail, includes details
                                    about all attempted providers and their errors
        """
        errors = []
        
        for provider in self.providers:
            provider_name = provider.get_provider_name()
            
            try:
                logger.debug(f"Attempting label generation with {provider_name}")
                start_time = time.time()
                
                # Attempt label generation
                label = provider.generate_label(prompt, max_tokens)
                
                # Calculate elapsed time
                elapsed_ms = (time.time() - start_time) * 1000
                
                # Update statistics for successful call
                stats = self.stats[provider_name]
                stats.successful_calls += 1
                stats.total_response_time_ms += elapsed_ms
                
                logger.info(f"Label generated by {provider_name} in {elapsed_ms:.0f}ms")
                return label
                
            except ProviderError as e:
                # Expected provider errors (rate limit, auth, timeout, etc.)
                error_msg = f"{provider_name}: {str(e)}"
                errors.append(error_msg)
                
                # Update statistics for failed call
                self.stats[provider_name].failed_calls += 1
                
                logger.warning(f"Provider {provider_name} failed: {e}")
                continue
            
            except Exception as e:
                # Unexpected errors
                error_msg = f"{provider_name}: Unexpected error - {str(e)}"
                errors.append(error_msg)
                
                # Update statistics for failed call
                self.stats[provider_name].failed_calls += 1
                
                logger.error(f"Provider {provider_name} unexpected error: {e}")
                continue
        
        # All providers failed - raise comprehensive error
        error_summary = "; ".join(errors)
        raise AllProvidersFailedError(
            f"All providers failed to generate label. Attempted providers: "
            f"{[p.get_provider_name() for p in self.providers]}. Errors: {error_summary}"
        )
    
    def get_statistics(self) -> Dict[str, ProviderStats]:
        """Return usage statistics for all providers.
        
        Returns:
            Dictionary mapping provider name to ProviderStats object
        """
        return self.stats.copy()
    
    def get_summary(self) -> str:
        """Return formatted summary of provider usage.
        
        Generates a multi-line string with statistics for each provider
        including success rate and average response time.
        
        Returns:
            Multi-line string with usage summary
        """
        lines = ["Provider Usage Summary:"]
        
        for name, stats in self.stats.items():
            total = stats.successful_calls + stats.failed_calls
            
            if total > 0:
                success_rate = (stats.successful_calls / total) * 100
                avg_time = (stats.total_response_time_ms / stats.successful_calls 
                           if stats.successful_calls > 0 else 0)
                
                lines.append(
                    f"  {name}: {stats.successful_calls}/{total} successful "
                    f"({success_rate:.1f}%), avg response time {avg_time:.0f}ms"
                )
            else:
                lines.append(f"  {name}: No calls made")
        
        return "\n".join(lines)
